version: '3.8'
services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=140850
      - POSTGRES_DB=usuario-service-db
    volumes:
      - postgresql_data:/bitnami/postgresql
    ports:
      - "5432:5432"
volumes:
  postgresql_data:
    driver: local